FROM --platform=linux/amd64 696230526504.dkr.ecr.us-east-1.amazonaws.com/allora-inference-base:dev-latest

COPY requirements.txt /app/
RUN pip3 install --requirement /app/requirements.txt

COPY main.py /app/
